### ISSUE TITLE
Gluetun setup possible?

### ISSUE THREAD

**Issue by puppinoo** [skjaere/DebriDav#3]
Hi,
Title says basically all.
Is Gluetun https://github.com/qdm12/gluetun integration possible?

Thanks.

**Comment by skjaere** [comment]
I think so, yes, but I don't know enough about networking with docker to provide much assistance unfortunately. 
If you're using the docker-compose.yaml in example it might be as simple as adding `driver: service:gluetun` under `networks.debridav-network` so it looks like this:
```
networks:
  debridav-network:
    driver: service:gluetun

```

I haven't tested it though. I will close this issue as this is a question that relates to Gluetun and Docker, not DebriDav.
Good luck!
